apiVersion: v1
kind: ConfigMap
metadata:
  name: ncba-config
  namespace: ncba
data:
  DB_HOST: mysql-service
  DB_USER: root
  RABBITMQ_HOST: rabbitmq

---
apiVersion: v1
kind: Secret
metadata:
  name: ncba-secrets
  namespace: ncba
type: Opaque
stringData:
  DB_PASSWORD: root
  RABBITMQ_USER: guest
  RABBITMQ_PASSWORD: guest
